### ISSUE TITLE
Sample code in 'Day of scheduled replacement' section of the 'Implementing Vanilla certificate replacement' article

### ISSUE THREAD

**Issue by snijderr** [sdl/ISHDeploy#1]

**Comment by snijderr** [comment]
The documentation article 'Implementing Vanilla certificate replacement' contains a sample script in the 'Day of scheduled replacement' section, which contains an incorrect parameter reference.

According to the sample script the 'Set-ISHSTSConfiguration' commandlet has the following parameter list '-ISHDeployment $deploymentName -Thumbprint $certificateThumbprint'.
However the Commandlet documentation shows that it is not containing the -Thumbprint argument but the -TokenSigningCertificateThumbprint argument

**Comment by Sarafian** [comment]
Thanks @snijderr . We'll fix this with the next release.

**Comment by Sarafian** [comment]
Fixed with version 1.2
